In [1]:
import numpy as np

### XOR

In [2]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0,1,1,0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
# ACTIVATION - Sigmoid Function
def sig(z):
    return 1 / (1 + np.exp(-z))

In [4]:
# Derivative of Sigmoid Function
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [5]:
n_input = 2
n_hidden_1 = 2
n_output = 1
lr = 0.1
epochs = 10000

In [6]:
weights = {
    'h1': 2 * np.random.random((n_input, n_hidden_1)) - 1,
    'out': 2 * np.random.random((n_hidden_1, n_output)) - 1
}

biases = {
    'h1': 2 * np.random.random((1, n_hidden_1)) - 1,
    'out': 2 * np.random.random((1, n_output)) - 1
}

In [7]:
# # one hidden layer weights
# wh = 2 * np.random.random((2, 2)) - 1
# bh = 2 * np.random.random((1, 2)) - 1
# wo = 2 * np.random.random((2, 1)) - 1
# bo = 2 * np.random.random((1, 1)) - 1
# lr = 0.1

In [22]:
for iter in range(epochs):
    # Forward Propagation
    inputHidden = np.dot(X, weights['h1']) + biases['h1']
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden, weights['out']) + biases['out']
    output = sig(inputForOutputLayer)

    # Backpropagation
    first_term_output_layer = output - Y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer * second_term_output_layer
    
#     print(output.shape)
#     print(Y)
#     print(first_two_output_layer.shape)
    

    first_term_hidden_layer = np.dot(first_two_output_layer, weights['out'].T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    changes_output = np.dot(outputHidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis = 0, keepdims = True)

    changes_hidden = np.dot(X.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0, keepdims = True)

    weights['out'] = weights['out'] - lr*changes_output
    biases['out'] = biases['out'] - lr*changes_output_bias

    weights['h1'] = weights['h1'] - lr*changes_hidden
    biases['h1'] = biases['h1'] - lr*changes_hidden_bias


inputHidden = np.dot(X, weights['h1']) + biases['h1']
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden, weights['out']) + biases['out']
output = sig(inputForOutputLayer)

print('Output: \n', output)
print('\n\nWeights Hidden: \n', weights['h1'])
print('\n\nBias Hidden: ', biases['h1'])
print('\n\nWeights Output: \n', weights['out'])
print('\n\nBias Output: ', biases['out'])

Output: 
 [[0.10965573]
 [0.89758352]
 [0.8977523 ]
 [0.12540683]]


Weights Hidden: 
 [[-3.77768078  5.89218234]
 [-3.77181001  5.85851676]]


Bias Hidden:  [[ 5.62203675 -2.45744318]]


Weights Output: 
 [[5.82686285]
 [5.6652099 ]]


Bias Output:  [[-8.34708603]]
